version: '3.8'

services:
  postgres-db:
    image: postgres
    container_name: postgres-db6
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"
    networks:
      - techcell-network

  spring-boot-app:
    image: spring-boot-docker
    container_name: techcell-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres-db
    networks:
      - techcell-network

networks:
  techcell-network:
    driver: bridge
